basePath: /api/v1
definitions:
  models.News:
    properties:
      author:
        type: string
      body:
        type: string
      created:
        example: "2020-04-21T00:00:00Z"
        type: string
      id:
        type: integer
    type: object
info:
  contact: {}
  description: API documentation for News Api
  license:
    name: Apache 2.0
    url: http://www.apache.org/licenses/LICENSE-2.0.html
  title: News Api
  version: 1.0.0
paths:
  /news:
    get:
      description: Get the list of news
      operationId: list-news
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            items:
              $ref: '#/definitions/models.News'
            type: array
      summary: List news
      tags:
      - news
    post:
      description: Create a new news
      operationId: create-new
      parameters:
      - description: Create new
        in: body
        name: new
        required: true
        schema:
          $ref: '#/definitions/models.News'
      produces:
      - application/json
      responses:
        "201":
          description: Created
          schema:
            $ref: '#/definitions/models.News'
      summary: Create a new news
      tags:
      - news
  /news/{id}:
    get:
      description: Get an news by id
      operationId: get-new
      parameters:
      - description: News ID
        in: path
        name: id
        required: true
        type: integer
      produces:
      - application/json
      responses:
        "200":
          description: OK
          schema:
            $ref: '#/definitions/models.News'
      summary: Get an news
      tags:
      - news
swagger: "2.0"
