// Code generated by mockery v0.0.0-dev. DO NOT EDIT.

package mocks

import mock "github.com/stretchr/testify/mock"

// KafkaService is an autogenerated mock type for the KafkaService type
type KafkaService struct {
	mock.Mock
}

// SendMessage provides a mock function with given fields: msg
func (_m *KafkaService) SendMessage(msg string) error {
	ret := _m.Called(msg)

	var r0 error
	if rf, ok := ret.Get(0).(func(string) error); ok {
		r0 = rf(msg)
	} else {
		r0 = ret.Error(0)
	}

	return r0
}
